### ISSUE TITLE
The addon can not enable

### ISSUE THREAD

**Issue by SHIELDXIE** [eXzacT/RePrimitive#1]
### The addon can not enable   

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.1.0-stable+v31.c77597cd0e15-windows.amd64-release\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'RePrimitive-1'
![image](https://user-images.githubusercontent.com/37254173/161469009-d465c150-774d-49ac-9194-ecb6b5aadb34.png)

**Comment by eXzacT** [comment]
Hi again, I just installed it on 3.1 and there's no issues. Is that the
version you have? Did you just install it and enable it and you got the
error or was it after?

pon, 4. tra 2022. 18:46 Damjan Andelkovic ***@***.***> je
napisao:

**Comment by SHIELDXIE** [comment]
Hi,Thinks for your reply.When I try to turn it on in the plugin panel, it reports an error
blender version:3.10.2  and this is my system info
[system-info.txt](https://github.com/eXzacT/RePrimitive/files/8414299/system-info.txt)

![image](https://user-images.githubusercontent.com/37254173/161664046-fe7bd68e-96c3-4506-a078-e64f2dce40e7.png)

**Comment by eXzacT** [comment]
Okay I figured it out. In order to make it work you could either rename the Reprimitive-1.0 Folder to Reprimitive inside C:\Users\..\AppData\Roaming\Blender Foundation\Blender\version\scripts\addons 
or download from "Code"
![Fix](https://user-images.githubusercontent.com/49790173/161669444-d1b50525-26d0-4d19-892a-74ef8c0dca45.png)
not from Releases because it appends -1.0 to the end
The Releases tab on github is so the addon updater would work, don't download from there manually.
Sorry for the inconvenience, let me know if that fixes the problem.

**Comment by SHIELDXIE** [comment]
### I retry to install it.Now it can enable,but the `RePrimitive` still not working.
![image](https://user-images.githubusercontent.com/37254173/161674676-eb1e8635-7f9f-49d7-be0b-b2b4657832d4.png)

## blender system console 
`location: <unknown location>:-1
Python: Traceback (most recent call last):
  File "C:\Users\xnuon\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RePrimitive-main\ui.py", line 19, in poll
    return context.object is not None and bpy.context.preferences.addons['RePrimitive'].preferences.show_reprimitive_panel
KeyError: 'bpy_prop_collection[key]: key "RePrimitive" not found'`

**Comment by eXzacT** [comment]
That error should be fixed now, uninstall it and redownload from github.
But the button will still be greyed out(you won't be able to press it) because of this
![Names](https://user-images.githubusercontent.com/49790173/161680449-5e57939c-aa5a-4025-b0a3-ff6cfcca4449.png)
The mesh name has to be in english like this "Cylinder", I assume because your blender is in chinese it's also renaming the object. 
That's how the addon knows which operator to call.

**Comment by eXzacT** [comment]
I added chinese translations. It should work for chinese aswell, you don't have to rename anything.
Please let me know if it works, thanks.

**Comment by SHIELDXIE** [comment]
Now it can work. When I renamed it to English, it worked fine. but in chinese it still be greyed.
![9a710007abddc60ff34c6087177a281](https://user-images.githubusercontent.com/37254173/161713990-b286802c-17b8-4f8e-a99d-986bd544d384.png)
![32b4b196572e690825d798313ec7e5b](https://user-images.githubusercontent.com/37254173/161714011-e77f4f56-f334-4019-b023-96bb4825423f.png)

**Comment by eXzacT** [comment]
Did you download the latest version? Because i made a change in the meantime. It should work
![Chinese](https://user-images.githubusercontent.com/49790173/161733481-8d09b532-2178-42f6-b415-94ec84b18dc3.png)

**Comment by SHIELDXIE** [comment]
Yes. It is the latest version. I saw it in the code
![bb3873c82da9370ded7e05139b38d55](https://user-images.githubusercontent.com/37254173/161751277-1b4b05d1-01f1-4d42-a892-0e9d2e2a582a.png)

**Comment by eXzacT** [comment]
Can you try using it again in blender? Because when you uninstall and install addons in blender you have to restart it every time. If you didn't restart after installing the new one blender doesn't load all files correctly.

**Comment by SHIELDXIE** [comment]
It's running perfectly now，Thank you for your work.

**Comment by eXzacT** [comment]
No problem, thank you for using it and let me know if you encounter any bugs, I'll work on them as soon as possible :)

**Comment by eXzacT** [comment]
Thanks for letting me know, I'll check in a moment.

pon, 4. tra 2022. 05:28 SHIELDXIE ***@***.***> je napisao:
