### ISSUE TITLE
Expanding functionality of the addon via pie-menu 

### ISSUE THREAD

**Issue by AVA3d** [eXzacT/RePrimitive#6]
Damjan, I'd like to share a cool idea that came to me. 

What if instead of complex checks you'll add a 8-section pie-menu instead?

Advantages:
1. no need for complex coding for you with headache regarding tricky checks, proper naming and renaming
2. a user can choose what he would like to modify. AND! **_This way we also can CONVERT!!! one primitive into another! Change a cube into a cylinder, a cone into a sphere etc.!_** 
3. using the pie-menu is a VERY convenient way of working - in couple of days there is a muscle memory formed for frequently used menus

I've already made a semi-workable prototype as proof of the concept (no coding from my side, just using Pie Menu Editor Addon):
Video1: 
https://github.com/eXzacT/RePrimitive/assets/84742853/2e8ea9c6-fcea-4a59-9643-4bec85e7c18e

Video2 (booleans/BoxCutter):
https://github.com/eXzacT/RePrimitive/assets/84742853/7613a582-ba7a-4f83-a9a7-333a5c6a9774

This thing can expand the functionality of your addon substantially :)

**Comment by eXzacT** [comment]
That's a pretty good idea, however the issue here is that going from 1 object to another, I can't guarantee what would happen as the scripts are tailored to each object, it's possible that the object ends up being huge or even worse problems.
I can't say for sure as I never tested the operators for a different object type than the object actually is, as there was no need to do so.
It did seem to work fine with your examples though.
Also I think there has to be a different math-y way to figure out which object it is without fixing their rotations, but I remember not being able to come up with one before.

**Comment by eXzacT** [comment]
Side note, my laptop is falling apart when I'm running a boolean with an exact solver, is that happening for you guys too?
Even if I am just moving the cutter around and not using reprimitive on it.
I've fixed the parenting and booleans losing track of a cutter object, there's still some bugs left when the location/rotation is applied though, probably finishing that today along with adding loop cuts.

**Comment by AVA3d** [comment]
`I can't guarantee what would happen as the scripts are tailored to each object`

You can add to the description that besides the main functionality the addon has an another conversion feature, but it's outcome can not be 100% predicted and it's up to the user experimenting with it. 

Regarding huge sizes - is it possible to implement bounding-box check of the initial mesh and make the resulting mesh similar to it? Somewhere in the future, as 2nd grade task. As the main thing now, I guess,  is the preserving the initial state of the object - parenting, origin, booleans and shading(wired/solid, smooth/flat)

**Comment by eXzacT** [comment]
The other problem with this is that I would also need to create a built in pie menu because not everyone has it and it does add some work for the user which is what I'm trying to avoid, I think most people wouldn't want to choose which operator to use and would prefer if the addon figured out

**Comment by AVA3d** [comment]
`Side note, my laptop is falling apart when I'm running a boolean with an exact solver, is that happening for you guys too?`
Only on very dense meshes. On something simple like in the videos above - all works fine. 
Besides hardware power , you can check if some other addons (like Kit OPS) take resources of your laptop.

**Comment by AVA3d** [comment]
`some work for the user which is what I'm trying to avoid`
Well, there is still no such a button "make me a prop without any efforts". Even with all the fuss around AI...

To be serious. Do you mean it can be confusing to a user to choose proper option in the menu?
Well, if you want you can preserve the current one-button implementation and add the pie-menu as advanced option for another hothey.

**Comment by eXzacT** [comment]
Yes I know, I was thinking about that as an option, that one might take a while though because I don't know how long it would take me to add a pie menu, I'm thinking since it exists as a separate addon it's probably not easy at all

**Comment by eXzacT** [comment]
https://gifyu.com/image/SUFh2

**Comment by eXzacT** [comment]
I suppose a simpler thing would be to just add the quick rename mesh

**Comment by AVA3d** [comment]
`https://gifyu.com/image/SUFh2`
It looks like everything  is fixed! I'm eager to try it :))

Reg. PME  - this is really complex addon with a lot of functionality. I barely use 50% of it...  I'm not a programmer, and can't give you any advice regarding it unfortunately. But I think it shouldn't be too complex to create 8-section pie menu. I believe I've seen something regarding it on youtube.

**Comment by AVA3d** [comment]
Here is a video on YT: https://www.youtube.com/watch?v=41fXtvzJ3Ik&t=8s
I hope it might help

**Comment by eXzacT** [comment]
I'll see if I can do it after work, also the loop cuts.
Thanks for the help :)

**Comment by eXzacT** [comment]
Which object do you use most for cutters, I assume cylinders? If you want I can make it work for word Cutter aswell but it will assume it's a cylinder.
I'll upload the files here because it's not fully finished for a release yet

**Comment by eXzacT** [comment]
[RePrimitive.zip](https://github.com/eXzacT/RePrimitive/files/14620805/RePrimitive.zip)

**Comment by AVA3d** [comment]
Well... there aren't one most shape for cutters. All variations of cubes, cylinders and n-gons are used quite often. No, thanks. I think I'll stick with the menu approach - it's more flexible for my needs.  

`RePrimitive.zip`
Answered in the "Boolean / Parenting / Vieport Display" topic

**Comment by AVA3d** [comment]
Oh, man! It's so cool be able to work like this thanks to your addon!

https://github.com/eXzacT/RePrimitive/assets/84742853/68d51967-8564-4bc5-b367-887ba80e3057

**Comment by eXzacT** [comment]
I'm glad you're having fun :)

**Comment by eXzacT** [comment]
is there any point adding loop cut support for toruses or is it just for cylinders/cones?

**Comment by AVA3d** [comment]
No, adding support for cylinders/cones is enough.

Bu the way, I'm going to try add an another item in the pie-menu - Cube (4 sided cylinder + 45 degree rotation). It could be useful for faster conversion.

**Comment by eXzacT** [comment]
I don't know if I want to add the pie menu, because going from 1 object to another one makes no sense, I mean calculation-wise
but I do have to figure out a way for Cutters to also be accepted as a name and to pick the correct operator that gets called.
I don't know if there's a nice way to do that other than going down a huge tree and deciding which path to take and once you reach the end of a path you can say with 100% certainty what kind of shape it was

**Comment by AVA3d** [comment]
An another use case I've found for RePrimitive :)

https://github.com/eXzacT/RePrimitive/assets/84742853/d4b9197f-24f8-49d3-8247-27af7d9e409f

**Comment by eXzacT** [comment]
That looks funky ahahhahaha 😄

**Comment by eXzacT** [comment]
I'll be working on the addon again this weekend, been busy

**Comment by eXzacT** [comment]
Can you tell me if a cutter is always parented to the object it's cutting? Or is that not always the case, because right now it's looking for modifiers that a parent has, I would have to change it to go through every object in the scene and check if some have modifiers that are linked to the object you're changing, which might be costly depending on the scene but probably fine,
also would you like the loop cuts to get reapplied after changing the object? That might be a bit tricky since I can't really know where to put those cuts again, I guess I could get the height of a cut and what's the percentage of total height, then reapply it at that height percentage

**Comment by AVA3d** [comment]
"Can you tell me if a cutter is always parented to the object it's cutting?" - if we're talking about BoxCutter, than yes, it always parents a cutter as well as creates the folder Cutters, and put there the cutter as well. 
Hmm.. I'm not sure I understand why it's necessary to looking for modifiers, but it's technical things I'm not competent with :)

 " would you like the loop cuts to get reapplied after changing the object?" - if it's possible, it could be very handy for cylinders and cones. Probably it's worth to  implement it via checkmark? Good idea regarding height! I don't know if this is useful but BC orients cutters along Z axis:

https://github.com/eXzacT/RePrimitive/assets/84742853/562f482f-3fec-46a3-9c2f-3c804adaab36

**Comment by eXzacT** [comment]
Because the object you are changing is the target in the boolean modifier of the parent object, so when I delete the old objects I have to point the parent at the new one, I'm guessing that's one of the reasons they put it as a parent so they can easily track which objects have cutters and which cutters are cutting what.

Okay I'll see about reapplying the loopcuts at the correct heights again, I'll send the fixes I've doen so far here later today :)

**Comment by eXzacT** [comment]
Set it as not planned since I think I can solve it in a better way, I've done the rest you mentioned here though(I think), please let me know if you find any issues I'll get to fixing them as soon as I can, thanks :)

**Comment by AVA3d** [comment]
Great job Damjan! :)
RePrimitive preserves origin now, the same thing with Flat/Smooth. Working with the addon is very comfortable now!

**Comment by eXzacT** [comment]
Thank you, glad you found it helpful :D

**Comment by AVA3d** [comment]
Looks like we didn't notice the elephant in the room :D
There are couple of problems if we edit a source object:
1. with parenting;
2. loss of a boolean if we edit a cutter AFTER editing the source object

https://github.com/eXzacT/RePrimitive/assets/84742853/52b0b914-fb56-43a2-bb15-50b0aa9cc1e8

**Comment by eXzacT** [comment]
Oh of course, I should have thought of that 🤦, fixing it right now

**Comment by eXzacT** [comment]
[RePrimitive.zip](https://github.com/eXzacT/RePrimitive/files/14763330/RePrimitive.zip)
I think it works now, can you please check if I understood you correctly?

**Comment by AVA3d** [comment]
Yeah, you fixed these 2 issues! *thumbs up
Though I've noticed it creates unnecessary duplicate:
https://github.com/eXzacT/RePrimitive/assets/84742853/aeb9e87a-1b8c-44d1-ac53-bec6db718126

Could you also add preserving shading?

**Comment by AVA3d** [comment]
One more thought. Probably it would be better if scaling of an object could work from the origin.
https://github.com/eXzacT/RePrimitive/assets/84742853/49dfb642-b9fe-47ad-a618-68344401791f

 What do you think?

**Comment by eXzacT** [comment]
> Yeah, you fixed these 2 issues! *thumbs up Though I've noticed it creates unnecessary duplicate: https://github.com/eXzacT/RePrimitive/assets/84742853/aeb9e87a-1b8c-44d1-ac53-bec6db718126
> 
> Could you also add preserving shading?

I'm not sure what's wrong in the video, shading should work, is that the right click -> shade smooth?

**Comment by eXzacT** [comment]
Oof the scaling might be really hard, I have to check it out, when you change radius/depth I think it's different from the "s" scaling one, but I could be wrong

**Comment by AVA3d** [comment]
![2024-03-27_1](https://github.com/eXzacT/RePrimitive/assets/84742853/d33b5465-b6f0-4fcf-b2ad-a81e4f63d3d9)
I think it's Shade Auto Smooth. Though there are some changes in Blender 4.1 regarding shading. I haven't test 4.1 yet, but I heard this option removed completely and replaced by either a modifier or geometry node modifier (not 100% sure)

**Comment by eXzacT** [comment]
As far as I know, there is no way for me to tell whether shade smooth OR shade smooth(auto) was used on an object, so I can't know which of those two to reapply. Right now I'm reapplying shade smooth which is why the code doesn't work for you.
Maybe the best thing I can do is just always shade smooth auto it(if either was used) if that one is generally more used

**Comment by eXzacT** [comment]
False alarm sorry, I can find out which shading was used

**Comment by AVA3d** [comment]
This smoothy thing is subject to change in B4.1, so please don't invest to much time into it. 
I need a couple of days to figured out all the changes that B4.1 has brought, since it was released yesterday.

**Comment by eXzacT** [comment]
It was just couple lines of code to change it(I think it should work fine now)
I'm trying to reproduce the bug where it created duplicates but it doesn't happen to me, was it in that specific scenario or is it creating duplicates constantly?

**Comment by eXzacT** [comment]
Oh maybe because you're on 4.1

**Comment by AVA3d** [comment]
No, I'm on still 4.0.3
I guess this has to do with additional collections in the project.

**Comment by AVA3d** [comment]
Nope, this is related with the selection state of a collection:

https://github.com/eXzacT/RePrimitive/assets/84742853/7b2b7491-71f0-40d2-8cf5-4bc9b7af6d38

**Comment by AVA3d** [comment]
It creates a duplicate if something other than the Cutters and initial Collection folders is selected

**Comment by eXzacT** [comment]
I don't think it's a duplicate, just linked to two different collections at once

**Comment by eXzacT** [comment]
but I still don't know how to recreate the bug, could you do it manually without boxcutter creating some collections?

**Comment by eXzacT** [comment]
I think I'm supposed to unlink it from the default blender collection where objects get added if it wasn't there to begin with, let me check after meeting

**Comment by AVA3d** [comment]
> I don't think it's a duplicate, just linked to two different collections at once

Yes, you're right. 

> but I still don't know how to recreate the bug,

I can send you the file: 
[RePrimitive_01_2.zip](https://github.com/eXzacT/RePrimitive/files/14770380/RePrimitive_01_2.zip)



> could you do it manually without boxcutter creating some collections?

Checking it atm

**Comment by AVA3d** [comment]
The same thing without using BC:

https://github.com/eXzacT/RePrimitive/assets/84742853/9f9a3725-bc8e-4a32-80b2-142c6eedf3f1

**Comment by eXzacT** [comment]
Yep it's as I suspected, I thought about it when originally writing the code but I forgot, by default when we add new objects they go to the scene collection so I was linking it to the previous collection correctly but didn't unlink it from default if it wasn't inside it

[RePrimitive.zip](https://github.com/eXzacT/RePrimitive/files/14771298/RePrimitive.zip)
I think it should work now, also the shading

**Comment by AVA3d** [comment]
Super! All works smoothly!

**Comment by eXzacT** [comment]
Awesome, I'll wait a bit before releasing it because I'm sure you'll find something else hahahahahah

**Comment by AVA3d** [comment]
Hahaha! )))
Sorry man, this really isn't my goal to bother you with my discoveries :)

**Comment by eXzacT** [comment]
hahahaha it's not a problem, good that someone finds it

**Comment by AVA3d** [comment]
I've been trying to implement a preset system via PME. Something like this:
![2024-03-27_2](https://github.com/eXzacT/RePrimitive/assets/84742853/604b153b-f2fa-4e0e-bfe3-417322a82c3c)

Unsuccessfully yet unfortunately :(

Is there a proper command or a way to run a pre-created in RePremitive preset?

I tried 3 methods:

1. Run one command:
![2024-03-27_3](https://github.com/eXzacT/RePrimitive/assets/84742853/e210e5fc-4e7e-40bd-8328-e4d0ccb9ecac)

2. Run the command + execute the preset:
![2024-03-27_5](https://github.com/eXzacT/RePrimitive/assets/84742853/0e3efb56-bbda-409a-b4d3-1400fe78421e)

3. Record and run all these commands:
![2024-03-27_4](https://github.com/eXzacT/RePrimitive/assets/84742853/485e9516-f8b7-432c-8b55-b11cb38f6295)

**Comment by eXzacT** [comment]
you just want to spawn a specific primitive shape? you can just use the standard blender commands for that one
bpy.ops.mesh.primitive_cone_add(radius1=1, radius2=0, depth=2, enter_editmode=False, align='WORLD', location=(0, 0, 0), scale=(1, 1, 1)) but yeah you can't really spawn it where it was previously

**Comment by eXzacT** [comment]
oh I think I know what you mean, just do bpy.ops.object.reprimitive_*primitivename*
so either .reprimitive_cone
reprimitive_cylinder etc

**Comment by andelkovic-damjan** [comment]
The issue is operators I made don't support for input, they calculate everything by themselves, so calling them with some other data won't work because there is a lot of underlying data that is computed and you can't pass those

**Comment by AVA3d** [comment]
> you just want to spawn a specific primitive shape? you can just use the standard blender commands for that one

No, I want to create a button(s), which can run RePrimitive command, let's say Tweak Cylinder, and set necessary number of vertices (6/12/32.. etc).  

So instead of :
1. press hotkey
2. move the cursor to the field
3. manually type number of vertices  in that fielt

Do these steps:
1. press hotkey
2. click proper preset 
![2024-03-27_6](https://github.com/eXzacT/RePrimitive/assets/84742853/ab1a7c14-c519-4395-aed7-344995c2c5a7)

**Comment by AVA3d** [comment]
> oh I think I know what you mean, just do bpy.ops.object.reprimitive__primitivename_
> so either .reprimitive_cone
> reprimitive_cylinder etc

Yeah, that's the first thing I tied (№1 method ).

**Comment by andelkovic-damjan** [comment]
The thing is when you do bpy.ops.object.reprimitive_cylinder for example

![image](https://github.com/eXzacT/RePrimitive/assets/163007158/0c96548d-a602-4c02-8f5a-665a8ce64b53)

it is calling this function with those variables, and you don't have them defined because you essentially skip all the steps that are assigning those variables

**Comment by AVA3d** [comment]
So this command 
`bpy.ops.object.reprimitive_cylinder(vertices=32, depth=2.0, cap_fill='NGON', radius=1.0, b_UV=True, align='WORLD', operator_called_from_cancel=False)`

isn't enough to determine these variables?

**Comment by eXzacT** [comment]
yep those are just the ones that you see in the UI, and the ones that blender has when adding primitives too, there's a lot more hidden and you can't pass those

**Comment by eXzacT** [comment]
for example it's also passing the rotation, location and sure if you didn't apply it then you could just pass the current object location and rotation, but if either are applied there's quite some edge cases and you wouldn't be able to pass the correct data yourself

**Comment by eXzacT** [comment]
![image](https://github.com/eXzacT/RePrimitive/assets/49790173/4730614d-bc7f-4c91-b124-29fe49166e9c)

**Comment by AVA3d** [comment]
Damn, sometimes I regret I haven't invest my time in studying Python... 
It looks like PME addon can't help in this case.

**Comment by AVA3d** [comment]
One last idea. 
PME can run an exterior script. 
Could you please separate this necessary part of the code into the script? Tweak Cylinder, set 12 vertices. 
I could use this script as the example, and modify for other vertices.

**Comment by eXzacT** [comment]
Yeah I can help you set it up, tomorrow though :)

**Comment by AVA3d** [comment]
Sure, no hurry. When you have some time :)

**Comment by eXzacT** [comment]
I was wrong you can pass variables as long as you add 'INVOKE_DEFAULT' to the call, like this
bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT')
but whatever you pass will get overwritten anyway since I'm calculating it myself, are verts the only thing you care about? I can change it so it doesn't get calculated if it's passed

**Comment by AVA3d** [comment]
Yep, the idea is that a preset should set predefined amount of vertices, other than that it should work as the standard Tweak Cylinder tool (preserving radius, depth, origin, shading etc.).

**Comment by eXzacT** [comment]
[RePrimitive.zip](https://github.com/eXzacT/RePrimitive/files/14812920/RePrimitive.zip)

so the way you can use it is add the menu as you did in pie menu addon, and bind each button to different strings such as
bpy.ops.object.reprimitive_cone('INVOKE_DEFAULT', vertices=32)
bpy.ops.object.reprimitive_cone('INVOKE_DEFAULT', vertices=16)

bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT', vertices=32)
bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT', vertices=16)

bpy.ops.object.reprimitive_circle('INVOKE_DEFAULT', vertices=32)
bpy.ops.object.reprimitive_circle('INVOKE_DEFAULT', vertices=16)

I've only added it for those 3, wasn't sure if you wanted to do it for others too since they don't have verts but major and minor segments, also you can only add vertices=, others are overwritten

I've added a way to check what type an object is so you don't need to rename them anymore, they'll keep their original name and mesh name, there are some edge cases where it won't work like cylinder with 4 sides, since all the faces are quads I'll just assume it's a torus, also some cases with cones being pyramids but it should guess what type an object is for 99% cases

Could you please try instaling then closing blender and reopening and see if the keybinds still work? cause they don't for me, I want to know if I messed something up locally or for everyone

**Comment by AVA3d** [comment]
Testing it atm :)

> Could you please try instaling then closing blender and reopening and see if the keybinds still work? cause they don't for me, I want to know if I messed something up locally or for everyone

It looks keybindings work fine on my side. Tried uninstall->save->reload->install->save->reload. And my usual method: delete old files in the addon directory and copy the new ones.

**Comment by AVA3d** [comment]
Aren't there any conflicts in your Keymap?
![2024-03-31_1](https://github.com/eXzacT/RePrimitive/assets/84742853/018336a2-2f24-4495-a85c-c7ab1f070c74)

**Comment by eXzacT** [comment]
Oh it's because I rebound it when I was testing a specific function, thanks :)
Everything works as you expected it to?

**Comment by AVA3d** [comment]
Just super! Presets system works great!!! Very convenient to use it! Thank you so much Damjan!!!
In case you'd like to see how it works , I've recorded a demo:
https://github.com/eXzacT/RePrimitive/assets/84742853/a4a1e73f-e6f4-4274-935d-d149f9a621c8

I've noticed some changes in this version in the main tool, there is strange behavior with live update in the pop-up window. But it is probably with my setup only. I've been trying to figured it out, but no success yet (it's too late here and I'm half asleep ). I'll try tomorrow with a fresh head.

**Comment by eXzacT** [comment]
I was doing a lot of refactors again since I've made the addon like 2 or 3 years ago, so I might have changed some functionality during the refactors, everything seemed the same though

**Comment by eXzacT** [comment]
Pie menu is so cool but I can't implement it as going from 1 shape to another doesn't make sense, a lot of the code is specific to the shape you're working with so I can't guarantee there won't be no errors/crashes etc

**Comment by AVA3d** [comment]
A couple of observations regarding that live-update issue.

First, how it worked in previous 2.0.1 build: it was possible to tweak values in both windows (pop-up window and default undo window)
https://github.com/eXzacT/RePrimitive/assets/84742853/78fea1ac-0694-424f-80c7-22ab93298008

**Comment by AVA3d** [comment]
With the current build tweaking values in the pop-up window does nothing (though if we press Ok button it applies the values). I've noticed that it's related to the state of the  "operator_called_from_cancel" command.
It works fine in the default undo window:
https://github.com/eXzacT/RePrimitive/assets/84742853/2f0e04ca-e712-47c5-b50d-66323f35c197

**Comment by eXzacT** [comment]
love the question marks 😂, it works if you use it regularly but it doesn't when you pass the verts manually, should work with this one 
[RePrimitive.zip](https://github.com/eXzacT/RePrimitive/files/14816062/RePrimitive.zip)
It's a temporary fix but I have to look into what I was trying to do with those from_cancel and from_check booleans and if they're necessary at all, I vaguely remember having issues where execute was running twice so I added those extra checks for performance reasons. I have a plan of writing the calculated data into object meta data so it doesn't have to be calculated again, it should perform A LOT better that way, the downside is every object that was changed by the addon would have that metadata written inside them, which shouldn't be a big deal because it's just a couple of integers. It would also theoretically help a lot with loop cuts, so if you called the operator on an object without loop cuts, it would properly save all its data, then you could add loop cuts ad they wouldn't affect the already saved data, I could then reapply those loop cuts

**Comment by eXzacT** [comment]
actually it depends on how you use the addon, if you keep closing and calling the operators again then it computes it every time, but if you generally keep it open and just change it in the first popup or even in the bottom left it's just calculating twice, it would help with loop cuts though and any kind of destructive workflow as it would remember the data from the time the object wasn't changed drastically

**Comment by AVA3d** [comment]
It works for the first time now.  If I execute the command next time - the same thing as before. Also, if a preset was used previously, than it applies the exact number of vertices as it was in the preset.  

In case it has any importance , I noticed some changes in Data->Custom Properties section  (have no idea what it is and how to cook it :))

https://github.com/eXzacT/RePrimitive/assets/84742853/54b89501-aa74-4922-b696-555565c1e87c

**Comment by eXzacT** [comment]
In case it has any importance , I noticed some changes in Data->Custom Properties section, what do you mean by this, I am writing whether cone was sharp_tipped so I don't have to compute it twice, but then deleting the property afterwards, you shouldn't be able to see it
![screengif](https://github.com/eXzacT/RePrimitive/assets/49790173/a7e50f86-2c8e-482e-ab32-37ee1bac306f)

**Comment by eXzacT** [comment]
the bc, hops and the other one? it's from hardops not me, but maybe me adding a property is triggering theirs to show or something

**Comment by AVA3d** [comment]
> the bc, hops and the other one?

You mentioned metadata previously, so I thought it might me important for you to know that these ones are disappeared after using the addon :)

**Comment by eXzacT** [comment]
I'm not using that approach yet, currently only for the cone and 1 specific property is_sharp_tipped, you don't need to know about this but let's just say cones are such a pain... million edge cases 🤦‍♂️

**Comment by eXzacT** [comment]
Did you check my gif? Everything works fine for me idk what's the problem

**Comment by eXzacT** [comment]
> > the bc, hops and the other one?
> 
> You mentioned metadata previously, so I thought it might me important for you to know that these ones are disappeared after using the addon :)

Oh that might be a problem for other addons working with this one, I could just copy all the properties when creating a new object, but first let's see if it actually creates a problem, I am not using hops so idk what they use those properties for

**Comment by AVA3d** [comment]
> Did you check my gif? Everything works fine for me idk what's the problem

Yes, you're shooting presets commands. And presets work great (thank you again :)!

But try to run this one twice: 
bpy.ops.object.reprimitive_cylinder(operator_called_from_cancel=False)
 
Can you change values after second run in the pop-up window under the cursor?

**Comment by eXzacT** [comment]
bpy.ops.object.reprimitive_cylinder(operator_called_from_cancel=False)

don't call it like that
just do ('INVOKE_DEFAULT', vertices = ?)

**Comment by eXzacT** [comment]
if you want the addon to guess which operator should be called(should work in most cases, I have to take care of some edge ones)
then you can just do bpy.ops.object.reprimitive(), but it's even better if you manually call a specific operator since it skips to check which one it is

here you have to add 'INVOKE_DEFAULT'
bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT'), this one will calculate verts 
bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT',vertices = 20), this one will calculate them but overwrite with the ones you passed, so it will end up being 20

**Comment by AVA3d** [comment]
Man, you're a genius!!! 

This command works smoothly for the main tool(calculating vertices)  
> bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT')

And this one for pre-defined presets(buttons)
> bpy.ops.object.reprimitive_cylinder('INVOKE_DEFAULT',vertices = 20)

**Comment by eXzacT** [comment]
hahahahahahah let me know if you find something else :D
