### ISSUE TITLE
Reprimitive Italian Language

### ISSUE THREAD

**Issue by 47b3r70** [eXzacT/RePrimitive#7]
Hi eXzacT

I thank You for this Your excellent Addon for Blender, known thanks to Ponte Ryuurui, who talks about It in His last tutorial https://www.youtube.com/watch?v=LIPuzZqqxaI.
I use blender in Italian, and I modified the Italian part of the localization.py file, and partially translated operators.py, of Your Reprimitive Addon, otherwise it wouldn't work
Now RePrimitive works flawlessly with Sphere, Cone, Cylinder, Icosphere and Toroid, even if the Italian language is selected.
I attach the two files, and I thank You again for the excellent Addon.

GoodBye

Alberto

![2024-03-27 10_16_41-_ (Unsaved) - Blender 4 0](https://github.com/eXzacT/RePrimitive/assets/165147591/e8ff9de8-d8f5-4e78-9c0b-24f2e057dadb)

[Blender.zip](https://github.com/eXzacT/RePrimitive/files/14771250/Blender.zip)

**Comment by eXzacT** [comment]
Hi Alberto, that's awesome I like Ponte.
![image](https://github.com/eXzacT/RePrimitive/assets/49790173/12164a1c-413c-41dd-8cc3-390eb2b27e22)
these ones weren't working?

**Comment by eXzacT** [comment]
I think they must have changed it in some recent versions because I was manually changing language and copy pasting the names blender gave them, thank you, I'll make these changes for the next patch, also hopefully I can find a nice way to figure out what kind of an object it is without it having the correct name so there won't be any need for localizations

**Comment by eXzacT** [comment]
Can you tell me if the only thing you changed in the operator was the labels? If so that's not necessary for the addon to work, I don't have those localized, it's just an explaination what the operator does so I won't be localizing those
